#event.yml 파일지정 내용 포함시킴
spring:
  application:
    name: notification-consumer
  profiles:
    active: local
    include: event
  data:
    mongodb:
      uri: mongodb://localhost:27017/kafka-web
    redis:
      host: localhost
      port: 6379
server:
  port: 8082